"""initial_schema

Revision ID: 65bdade8759d
Revises: 
Create Date: 2026-08-19 13:31:27.836161

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65bdade8759d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_table('pressure_tests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('log_no', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pressure_tests_log_no'), 'pressure_tests', ['log_no'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('test_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pressure_test_id', sa.String(length=36), nullable=False),
    sa.Column('revision_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('operator', sa.String(length=128), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pressure_test_id'], ['pressure_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_revisions_pressure_test_id'), 'test_revisions', ['pressure_test_id'], unique=False)
    op.create_index(op.f('ix_test_revisions_revision_id'), 'test_revisions', ['revision_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_revision_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relative_path', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_revision_id'], ['test_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_sha256'), 'artifacts', ['sha256'], unique=False)
    op.create_index(op.f('ix_artifacts_test_revision_id'), 'artifacts', ['test_revision_id'], unique=False)
    op.create_table('bundles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_revision_id', sa.String(length=36), nullable=False),
    sa.Column('bundle_number', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['test_revision_id'], ['test_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bundles_bundle_number'), 'bundles', ['bundle_number'], unique=False)
    op.create_index(op.f('ix_bundles_test_revision_id'), 'bundles', ['test_revision_id'], unique=False)
    op.create_table('pipes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_revision_id', sa.String(length=36), nullable=False),
    sa.Column('pipe_number', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['test_revision_id'], ['test_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipes_pipe_number'), 'pipes', ['pipe_number'], unique=False)
    op.create_index(op.f('ix_pipes_test_revision_id'), 'pipes', ['test_revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipes_test_revision_id'), table_name='pipes')
    op.drop_index(op.f('ix_pipes_pipe_number'), table_name='pipes')
    op.drop_table('pipes')
    op.drop_index(op.f('ix_bundles_test_revision_id'), table_name='bundles')
    op.drop_index(op.f('ix_bundles_bundle_number'), table_name='bundles')
    op.drop_table('bundles')
    op.drop_index(op.f('ix_artifacts_test_revision_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_sha256'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_test_revisions_revision_id'), table_name='test_revisions')
    op.drop_index(op.f('ix_test_revisions_pressure_test_id'), table_name='test_revisions')
    op.drop_table('test_revisions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pressure_tests_log_no'), table_name='pressure_tests')
    op.drop_table('pressure_tests')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
